version: '3.3'
services:

  Notary:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
      - "10005:10005"
    image: corda/node:3.3
    container_name: notary
    volumes:
      - ./nodes/notary/:/opt/corda/
      - ./nodes/cordapps/:/opt/corda/cordapps/
      - ./nodes/notary/certificates/:/opt/corda/certificates/
      - ./nodes/notary/network-parameters:/opt/corda/network-parameters
      - ./nodes/notary/additional-node-infos/:/opt/corda/additional-node-infos

  CordaNodeA:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10022:10002"
      - "10023:10003"
      - "10024:10004"
      - "10025:10005"
    image: corda/node:3.3
    container_name: banka
    volumes:
      - ./nodes/banka/:/opt/corda/
      - ./nodes/cordapps/:/opt/corda/cordapps/
      - ./nodes/banka/certificates/:/opt/corda/certificates/
      - ./nodes/banka/network-parameters:/opt/corda/network-parameters
      - ./nodes/banka/additional-node-infos/:/opt/corda/additional-node-infos

  CordaNodeB:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10032:10002"
      - "10033:10003"
      - "10034:10004"
      - "10035:10005"
    image: corda/node:3.3
    container_name: bankb
    volumes:
      - ./nodes/bankb/:/opt/corda/
      - ./nodes/cordapps/:/opt/corda/cordapps/
      - ./nodes/bankb/certificates/:/opt/corda/certificates/
      - ./nodes/bankb/network-parameters:/opt/corda/network-parameters
      - ./nodes/bankb/additional-node-infos/:/opt/corda/additional-node-infos

  CordaNodeC:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10042:10002"
      - "10043:10003"
      - "10044:10004"
      - "10045:10005"
    image: corda/node:3.3
    container_name: bankc
    volumes:
      - ./nodes/bankc/:/opt/corda/
      - ./nodes/cordapps/:/opt/corda/cordapps/
      - ./nodes/bankc/certificates/:/opt/corda/certificates/
      - ./nodes/bankc/network-parameters:/opt/corda/network-parameters
      - ./nodes/bankc/additional-node-infos/:/opt/corda/additional-node-infos

networks:
  corda:
